# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

# Run on every push to main
on:
  push:
    branches:
      - main

# Give the Pages action permission to write
permissions:
  contents: read     # default for checking out code
  pages: write       # allow deploying to GitHub Pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code (don't reuse the read-only token)
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Setup Node
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install & build
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      # 4. Deploy to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
