# .github/workflows/deploy.yml

name: Build and deploy Estimator App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read   # for checkout
  pages: write     # for Pages publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
