# .github/workflows/deploy.yml

name: Build and deploy Estimator App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read   # needed to checkout code
  pages: write     # needed to publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3

      # 2. Setup Node.js 18
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install & build
      - run: npm ci
      - run: npm run build

      # 4. Upload the build folder as a deployment artifact
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build

      # 5. Deploy to GitHub Pages via the GitHub Pages API
      - uses: actions/deploy-pages@v1
